version: "3.8"

services:
  mongo:
    image: devnusair24/football-ecom-mongo:latest
    container_name: football-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: devnusair24/football-ecom-backend:latest
    container_name: football-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/football-ecom
      - JWT_SECRET=secret
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    image: devnusair24/football-ecom-frontend:latest
    container_name: football-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
